<script>
const password = "h2so4";  
const userPass = prompt("Enter password to access this page:");
if(userPass !== password){
  alert("Incorrect password! Redirecting...");
  window.location.href = "/";  // send them back to homepage
}
</script>

---
title: "Aerosols"
---

## Configurational Sampling
Description.

## DFT Optimizations
To start, make sure all xyz files from configurational sampling are in folders GA/20K, GA/20K-1, GA/200K, GA/PM7, etc.

At the same level as GA, make the directories QM/wb97xd-ultrafine. Copy all uniqueStructures-\*.data files to wb97xd-ultrafine/.

Within wb97xd-ultrafine, run **`opt_wb97xd.py uniqueStructures-PM7.data -h`** to see options for submission.

Once you are ready, run the command with your options set. Then, run **`sbatch run_gaussian.slurm`** to submit all jobs listed in the com_list.txt file.

Confirm that all optimizations have completed by running  **`check_opts.py`**. Any files that terminated early due to wall time limits will be printed to the screen. 

To rerun these, you can either:

1. **`sbatch --array=17,33 run_gaussian.slurm`** using the array number of the jobs that need to be rerun.

2. Update com_list.txt to include only the jobs that need rerunning. 

Wait for these jobs to finish, then run **`check_opts.py`** one more time to ensure that all optimizations have completed.

## Determine Unique Structures
**`getRotConsts-wb97xd.csh`**

**`similarityAnalysis.py uf rotConstsData_C`**

## Process Data



## DLPNO Single Point Energies
Make a directory within QM/wb97xd-ultrafine called dlpno.

Copy uniqueStructures-uf.data to dlpno/. Move into dlpno, and edit the dlpno/uniqueStructures-uf.data to include only the files with relative energies within 6-8 kcal/mol. (If you are unsure, consult someone.)

Run **`make_dlpno_inps.py`** to generate DLPNO-CCSD(T) input files and the slurm script. This script has the following options:

| Flag | Default | Description | Options |
|------|---------|-------------|-------------|
| \-\-aug   | \-\-aug=haug      | augmentation type of basis set          | haug, aug, or noaug    |
| \-\-zeta  | \-\-zeta=D,T,Q    | basis set zeta-levels  | D,T,Q,5,6 |
| \-\-nproc | \-\-nproc=12 | number of cores/processors | any integer (check `freestd`)|
| \-\-mem   | \-\-mem=100g | amount of SLURM memory per job | any integer followed by `g`|
| \-\-time | \-\-time=24:00:00 | wall time per job | hours:minutes:seconds |
| \-\-constraint | \-\-constraint=cpu_gen_cascadelake | CPU name | cpu_gen_broadwell, cpu_gen_sapphirerapids, cpu_gen_cascadelake, or none |
| \-\-scratch | \-\-scratch=shared | shared or local scratch | shared, local|

## 
